freebsd_ci_task:
  name: CI / FreeBSD

  freebsd_instance:
    image_family: freebsd-15-0-amd64-ufs

  install_script: |
    pkg install -y bcftools gmake py311-cython3 py311-mypy py311-pytest samtools

  env:
    CC: "clang -isystem /usr/local/include"
    MAKE: "gmake"
    REF_PATH: ":"

  build_script: |
    python setup.py build

  test_script: |
    PYTHONPATH="$(echo $PWD/build/lib.*)" pytest
