build_wheels_task:
  only_if: $CIRRUS_BRANCH =~ "release/.*" || $CIRRUS_TAG =~ "v0\..*"

  matrix:
    - compute_engine_instance:
        image_project: cirrus-images
        image: family/docker-builder-arm64
        architecture: arm64
        platform: linux
      matrix:
        - name: Build ARM Linux py3.6-9 wheels
          env:
            CIBW_BUILD: "cp36-* cp37-* cp38-* cp39-*"
        - name: Build ARM Linux py3.10-12 wheels
          env:
            CIBW_BUILD: "cp310-* cp311-* cp312-*"

    - name: Build ARM macOS wheels
      macos_instance:
        image: ghcr.io/cirruslabs/macos-ventura-base:latest
      env:
        CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"

  alias: build_wheels

  env:
    CIRRUS_CLONE_DEPTH: 1

    CIBW_SKIP: "*-musllinux_*"
    CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_28

  install_script: |
    python3 -m pip install cibuildwheel==2.16.2

  build_script: |
    cibuildwheel

  wheels_artifacts:
    path: wheelhouse/*.whl

upload_pypi_task:
  only_if: $CIRRUS_BRANCH =~ "release/.*" || $CIRRUS_TAG =~ "v0\..*"
  depends_on: build_wheels

  name: Publish ARM wheels

  container:
    image: python:latest

  env:
    CIRRUS_CLONE_DEPTH: 1
    API_BASEURL: https://api.cirrus-ci.com/v1
    TWINE_USERNAME: __token__

  install_script: |
    python3 -m pip install twine

  get_artifacts_script: |
    curl -sSLO $API_BASEURL/artifact/build/$CIRRUS_BUILD_ID/wheels.zip
    unzip -q wheels.zip

  upload_script: |
    case "$CIRRUS_TAG" in
    v0.*)
        export TWINE_REPOSITORY=pypi TWINE_PASSWORD=$PYPI_TOKEN ;;
    *)
        export TWINE_REPOSITORY=testpypi TWINE_PASSWORD=$TESTPYPI_TOKEN ;;
    esac

    echo Uploading wheels to $TWINE_REPOSITORY...

    python3 -m twine check wheelhouse/*.whl
    python3 -m twine upload --disable-progress-bar wheelhouse/*.whl
