os:
  - linux
  - osx

language: c

stages:
  - test
  - name: deploy
    if: tag IS present

env:
  matrix:
    - CONDA_PY=2.7
    - CONDA_PY=3.6
    - CONDA_PY=3.7
    - CONDA_PY=3.8
  global:
    - PYSAM_LINKING_TEST=1
    - TWINE_USERNAME=grepall
    - secure: bTbky3Un19NAl62lix8bMLmBv9IGNhFkRXlZH+B253nYub7jwQwPQKum3ct9ea+XHJT5//uM0B8WAF6eyugpNkPQ7+S7SEH5BJuCt30nv6qvGhSO2AffZKeHEDnfW2kqGrivn87TqeomlSBlO742CD/V0wOIUwkTT9tutd+E7FU=

_cibw_common: &cibw_common
  addons: {}
  install:
    - python3 -m pip install cibuildwheel>=1.1.0 twine
  script:
    - set -e
    - cibuildwheel --output-dir dist
    - twine check dist/*
    - twine upload --skip-existing dist/*

_cibw_linux: &cibw_linux
  stage: deploy
  os: linux
  language: python
  python: '3.5'
  services:
    - docker
  <<: *cibw_common

_cibw_linux_aarch64: &cibw_linux_aarch64
  stage: deploy
  os: linux
  arch: arm64
  language: python
  python: '3.9'
  services:
    - docker
  <<: *cibw_common

matrix:
  include:
    - stage: deploy
      os: linux
      language: python
      python: '3.5'
      addons:
        apt:
          packages:
            - gcc
            - g++
            - libcurl4-openssl-dev  # for libcurl support in sdist
            - libssl-dev  # for s3 support in sdist
      install:
        - python3 -m pip install Cython twine
      script:
        - set -e
        - python3 setup.py build_ext --inplace
        - python3 setup.py sdist
        - twine check dist/*
        - twine upload --skip-existing dist/*
    - <<: *cibw_linux
      env:
        - CIBW_BUILD="*_x86_64"
        - CIBW_BEFORE_BUILD="yum install -y zlib-devel bzip2-devel xz-devel && python -m pip install -r requirements.txt"
        - CIBW_ENVIRONMENT='HTSLIB_CONFIGURE_OPTIONS="--disable-libcurl"'
        - CIBW_REPAIR_WHEEL_COMMAND_LINUX='auditwheel repair -L . -w {dest_dir} {wheel}'
        - CIBW_TEST_COMMAND='python -c "import pysam"'
    - <<: *cibw_linux
      env:
        - CIBW_BUILD="*_i686"
        - CIBW_BEFORE_BUILD="yum install -y zlib-devel bzip2-devel xz-devel && python -m pip install -r requirements.txt"
        - CIBW_ENVIRONMENT='HTSLIB_CONFIGURE_OPTIONS="--disable-libcurl"'
        - CIBW_REPAIR_WHEEL_COMMAND_LINUX='auditwheel repair -L . -w {dest_dir} {wheel}'
        - CIBW_TEST_COMMAND='python -c "import pysam"'
    - <<: *cibw_linux_aarch64
      env:
        - CIBW_BUILD="*_aarch64"
        - CIBW_BEFORE_BUILD="yum install -y zlib-devel bzip2-devel xz-devel && python -m pip install -r requirements.txt"
        - CIBW_ENVIRONMENT='HTSLIB_CONFIGURE_OPTIONS="--disable-libcurl"'
        - CIBW_REPAIR_WHEEL_COMMAND_LINUX='auditwheel repair -L . -w {dest_dir} {wheel}'
        - CIBW_TEST_COMMAND='python -c "import pysam"'
    - stage: deploy
      os: osx
      language: generic
      env:
        - CIBW_BEFORE_BUILD="python -m pip install -r requirements.txt"
        - CIBW_ENVIRONMENT='HTSLIB_CONFIGURE_OPTIONS="--disable-libcurl"'
        - CIBW_TEST_COMMAND='python -c "import pysam"'
      <<: *cibw_common

addons:
  apt:
    packages:
    - gcc
    - g++

script:
  - ./devtools/run_tests_travis.sh

notifications:
  email:
    - andreas.heger@gmail.com
