/* confdefs.h */
#define PACKAGE_NAME "HTSlib"
#define PACKAGE_TARNAME "htslib"
#define PACKAGE_VERSION "1.7"
#define PACKAGE_STRING "HTSlib 1.7"
#define PACKAGE_BUGREPORT "samtools-help@lists.sourceforge.net"
#define PACKAGE_URL "http://www.htslib.org/"
#define HAVE_FSEEKO 1
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_STDLIB_H 1
#define HAVE_UNISTD_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_GETPAGESIZE 1
#define HAVE_GMTIME_R 1
#define HAVE_FSYNC 1
#define HAVE_DRAND48 1
#define HAVE_FDATASYNC 1
